import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";

// Initialize Gemini client with proper API key
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY!);

export async function POST(req: NextRequest) {
  try {
    // Check API key
    const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
    if (!apiKey) {
      console.error('Neither GOOGLE_API_KEY nor GEMINI_API_KEY found in environment variables');
      return NextResponse.json(
        { error: 'Google/Gemini API key not configured' },
        { status: 500 }
      );
    }

    const formData = await req.formData();
    const image = formData.get('image') as File;
    const prompt = formData.get('prompt') as string;
    const resizeWidth = formData.get('resize_width') as string;
    const resizeHeight = formData.get('resize_height') as string;

    if (!image || !prompt) {
      return NextResponse.json(
        { error: 'Image and prompt are required' },
        { status: 400 }
      );
    }

    // Validate image type
    if (!image.type.startsWith('image/')) {
      return NextResponse.json(
        { error: 'Please upload a valid image file' },
        { status: 400 }
      );
    }

    // Convert image to base64
    const bytes = await image.arrayBuffer();
    const buffer = Buffer.from(bytes);
    const base64Image = buffer.toString('base64');

    // Use Gemini 2.5 Flash Image (Nano Banana) for image generation/editing
    const imageModel = genAI.getGenerativeModel({ model: "gemini-2.5-flash-image-preview" });

    // Create optimized prompt for Gemini 2.5 Flash Image (Nano Banana)
    let enhancedPrompt = `${prompt}. Please edit the provided image according to this request and return the modified image.`;
    
    // Add specific instructions for resizing if dimensions are provided
    if (resizeWidth && resizeHeight) {
      enhancedPrompt = `${prompt} Please ensure the final image is exactly ${resizeWidth}x${resizeHeight} pixels with the specified aspect ratio and high quality.`;
      console.log(`Processing image resize to ${resizeWidth}x${resizeHeight} with Gemini 2.5 Flash Image (Nano Banana) model...`);
    } else {
      console.log('Processing image with Gemini 2.5 Flash Image (Nano Banana) model...');
    }

    // Generate the edited image using Gemini 2.5 Flash Image (Nano Banana)
    const result = await imageModel.generateContent([
      { text: enhancedPrompt },
      {
        inlineData: {
          mimeType: image.type,
          data: base64Image
        }
      }
    ]);

    const response = await result.response;
    
    // Check if the response contains image data
    const candidates = response.candidates;
    if (!candidates || candidates.length === 0) {
      throw new Error('No image generated by Gemini');
    }

    const candidate = candidates[0];
    const content = candidate.content;
    
    if (!content.parts || content.parts.length === 0) {
      throw new Error('No content parts in response');
    }

    // Look for image data in the response
    let imageData: string | null = null;
    for (const part of content.parts) {
      if (part.inlineData && part.inlineData.mimeType?.startsWith('image/')) {
        imageData = part.inlineData.data;
        break;
      }
    }

    if (!imageData) {
      // If no image data, fallback to text response explaining the limitation
      const textResponse = content.parts.find(part => part.text);
      console.warn('Gemini response:', textResponse?.text || 'No text response');
      
      return NextResponse.json({
        error: 'Gemini 2.5 Flash Image (Nano Banana) did not return image data. The model may be generating a text response instead of an edited image.',
        modelResponse: textResponse?.text || 'No response text available'
      }, { status: 422 });
    }

    // Convert base64 to buffer and return the processed image
    const processedBuffer = Buffer.from(imageData, 'base64');
    
    console.log('Successfully processed image with Gemini 2.5 Flash Image (Nano Banana)');

    return new NextResponse(processedBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'image/png',
        'Content-Disposition': 'inline; filename="gemini-processed-image.png"',
        'X-Processed-By': 'Gemini-2.5-Flash-Image-NanoBanana'
      },
    });

  } catch (error) {
    console.error('Error processing image with Gemini 2.5 Flash Image (Nano Banana):', error);
    
    // Provide detailed error information
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    
    // Check for specific API errors
    if (errorMessage.includes('SERVICE_DISABLED') || errorMessage.includes('403 Forbidden')) {
      return NextResponse.json(
        { 
          error: 'Generative Language API Not Enabled',
          details: 'The Generative Language API needs to be enabled in your Google Cloud project.',
          instructions: [
            '1. Visit Google Cloud Console',
            '2. Navigate to APIs & Services > Library', 
            '3. Search for "Generative Language API"',
            '4. Click "Enable"',
            '5. Or create a new API key at Google AI Studio (https://makersuite.google.com/app/apikey)'
          ],
          activationUrl: 'https://console.cloud.google.com/apis/library/generativelanguage.googleapis.com',
          model: 'gemini-2.5-flash-image-preview'
        },
        { status: 403 }
      );
    }

    if (errorMessage.includes('API_KEY_INVALID') || errorMessage.includes('401')) {
      return NextResponse.json(
        { 
          error: 'Invalid API Key',
          details: 'The provided Google/Gemini API key is invalid or expired.',
          instructions: [
            '1. Check that GEMINI_API_KEY is correctly set in your .env file',
            '2. Verify the API key is valid at Google AI Studio',
            '3. Ensure the API key has permissions for Generative Language API'
          ],
          model: 'gemini-2.5-flash-image-preview'
        },
        { status: 401 }
      );
    }
    
    return NextResponse.json(
      { 
        error: 'Failed to process image with Gemini 2.5 Flash Image (Nano Banana)',
        details: errorMessage,
        model: 'gemini-2.0-flash-exp'
      },
      { status: 500 }
    );
  }
}